// src/components/simulations/SetTheCheckpoint.jsx
// Station B: The Hydro-Pressure Aqueduct Governor (Grade 7 Real-World Hydraulic Engineering)
import React, { useState } from 'react';
import './Stations.css';
import { useAudio } from '../../hooks/useAudio.js';

const AQUEDUCT_SYSTEMS = [
  {
    id: 'alpine_hydro',
    name: 'Alpine Penstock Hydro-Electric Aqueduct',
    medium: 'Water Pressure',
    unit: 'PSI',
    rateName: 'Pressure gain per station',
    a1: 14,
    d: 6,
    zeroTerm: 8, // 14 - 6
    targetStation: 35,
    targetCorrect: 218, // 6*35 + 8
    farhanMistake: 'P_n = 6n + 14',
    context: 'Stepped mountain descent pipe powering high-altitude turbines',
  },
  {
    id: 'geothermal_well',
    name: 'Sub-Glacial Geothermal Borehole',
    medium: 'Core Temperature',
    unit: '°C',
    rateName: 'Thermal climb per 100m shaft',
    a1: 23,
    d: 8,
    zeroTerm: 15, // 23 - 8
    targetStation: 25,
    targetCorrect: 215, // 8*25 + 15
    farhanMistake: 'T_n = 8n + 23',
    context: 'Deep thermal exploration sensor shaft through volcanic strata',
  },
  {
    id: 'hyperbaric_tunnel',
    name: 'Glacier Deep Rail Tunnel Ventilation',
    medium: 'Air Density',
    unit: 'kPa',
    rateName: 'Pressure boost per booster station',
    a1: 19,
    d: 5,
    zeroTerm: 14, // 19 - 5
    targetStation: 40,
    targetCorrect: 214, // 5*40 + 14
    farhanMistake: 'D_n = 5n + 19',
    context: 'Underground pneumatic tunnel maintaining crew oxygen pressure',
  },
];

export default function SetTheCheckpoint({ onComplete, audioEnabled }) {
  const { narrate, stopAll, sounds } = useAudio(audioEnabled);
  const [sysIdx, setSysIdx] = useState(0);
  const [rateSlider, setRateSlider] = useState(4);
  const [offsetSlider, setOffsetSlider] = useState(14); // starts at Farhan's mistake
  const [testedFarhan, setTestedFarhan] = useState(false);
  const [governorLocked, setGovernorLocked] = useState(false);
  const [deepInput, setDeepInput] = useState('');
  const [feedback, setFeedback] = useState(null);
  const [turbineSpinning, setTurbineSpinning] = useState(false);
  const [success, setSuccess] = useState(false);

  const sys = AQUEDUCT_SYSTEMS[sysIdx];

  // Current formula generated by sliders
  const currentFormula = `${rateSlider}n ${offsetSlider >= 0 ? '+' : '−'} ${Math.abs(offsetSlider)}`;
  const predictedAt1 = rateSlider * 1 + offsetSlider;
  const isPerfectMatch = rateSlider === sys.d && offsetSlider === sys.zeroTerm;

  function testFarhanFormula() {
    stopAll();
    sounds.wrong();
    setTestedFarhan(true);
    setRateSlider(sys.d);
    setOffsetSlider(sys.a1); // Sets 6n + 14
    setFeedback({
      type: 'err',
      text: `PRESSURE BLOWOUT WARNING! At Station 1, formula ${sys.d}(1) + ${sys.a1} = ${sys.d + sys.a1} ${sys.unit}. But actual sensor reads ${sys.a1} ${sys.unit}! The first term (${sys.a1}) cannot be used as the constant.`,
    });
    narrate([{
      text: `Pressure blowout warning! Formula predicts ${sys.d + sys.a1} ${sys.unit} at Station 1, but the real sensor reads ${sys.a1}. The constant must be adjusted!`,
      style: 'emphasis',
    }]);
  }

  function handleLockGovernor() {
    stopAll();
    if (isPerfectMatch) {
      sounds.correct();
      setGovernorLocked(true);
      setFeedback({
        type: 'ok',
        text: `GOVERNOR SYNCHRONIZED! Zero-term offset c = ${sys.a1} − ${sys.d} = +${sys.zeroTerm}. Formula P_n = ${sys.d}n + ${sys.zeroTerm} matches all sensor telemetry perfectly!`,
      });
      narrate([{
        text: `Governor synchronized! Formula matches all sensor stations. Ready for deep turbine calibration!`,
        style: 'celebration',
      }]);
    } else {
      sounds.wrong();
      setFeedback({
        type: 'err',
        text: `Governor misaligned. Rate must equal common difference (${sys.d}), and offset must equal the zero-term (${sys.a1} − ${sys.d} = ${sys.zeroTerm}).`,
      });
      narrate([{
        text: `Governor misaligned. Adjust the rate and zero-term offset to match the telemetry.`,
        style: 'encouragement',
      }]);
    }
  }

  function handleCheckDeepTarget() {
    stopAll();
    const val = parseInt(deepInput, 10);
    if (val === sys.targetCorrect) {
      sounds.correct();
      setSuccess(true);
      setTurbineSpinning(true);
      setFeedback({
        type: 'ok',
        text: `HYDRO GENERATORS ONLINE! Station ${sys.targetStation} stabilized at exact ${sys.targetCorrect} ${sys.unit}! Turbines operating at 100% capacity!`,
      });
      narrate([{
        text: `Hydro generators online! Exactly ${sys.targetCorrect} ${sys.unit} confirmed at Station ${sys.targetStation}. Turbine running smoothly!`,
        style: 'celebration',
      }]);
      if (sounds.levelUp) setTimeout(() => sounds.levelUp(), 800);
      setTimeout(() => {
        if (onComplete) onComplete();
      }, 3500);
    } else {
      sounds.wrong();
      setFeedback({
        type: 'err',
        text: `Pressure calculation error: For Station ${sys.targetStation}, calculate ${sys.d}(${sys.targetStation}) + ${sys.zeroTerm}.`,
      });
      narrate([{
        text: `Multiply ${sys.d} by ${sys.targetStation}, then add ${sys.zeroTerm}.`,
        style: 'encouragement',
      }]);
    }
  }

  function nextSystem() {
    stopAll();
    setSysIdx((i) => (i + 1) % AQUEDUCT_SYSTEMS.length);
    setRateSlider(4);
    setOffsetSlider(14);
    setTestedFarhan(false);
    setGovernorLocked(false);
    setDeepInput('');
    setFeedback(null);
    setTurbineSpinning(false);
    setSuccess(false);
  }

  return (
    <div className="station-container">
      {/* Station Header */}
      <div className="station-top-header">
        <div className="station-badge-group">
          <span className="station-pill-label">STATION B · HYDRAULIC PRESSURE REGULATION</span>
          <h3 className="station-headline">💧 {sys.name}</h3>
          <p className="station-subtext">{sys.context}</p>
        </div>
        <div className="station-metric-pill">
          <span className="metric-title">TARGET CHECKPOINT</span>
          <span className="metric-val">Station {sys.targetStation}</span>
        </div>
      </div>

      {/* Interactive Mountain Aqueduct Diagram & Telemetry Oscilloscope */}
      <div className="hydro-sim-viewport">
        {/* Mountain Slope Pipe Diagram */}
        <div className="aqueduct-pipe-schematic">
          <div className="reservoir-dam">
            <span className="dam-label">DAM HEADWATER</span>
            <div className="water-reservoir-level"></div>
          </div>

          <div className="stepped-pipe-flow">
            {/* 4 Sensor Stations Along Pipe */}
            {[1, 2, 3, 4].map((stn) => {
              const actualPSI = sys.a1 + (stn - 1) * sys.d;
              const formulaPSI = rateSlider * stn + offsetSlider;
              const isDiff = testedFarhan && formulaPSI !== actualPSI;

              return (
                <div key={stn} className={`pipe-checkpoint-node ${isDiff ? 'sensor-warning' : 'sensor-nominal'}`}>
                  <div className="gauge-dial">
                    <div
                      className="gauge-needle"
                      style={{
                        transform: `rotate(${Math.min(130, Math.max(-130, (actualPSI - 20) * 4))}deg)`,
                      }}
                    ></div>
                  </div>
                  <div className="sensor-info">
                    <span className="sensor-stn">Stn {stn}</span>
                    <span className="sensor-psi">{actualPSI} {sys.unit}</span>
                  </div>
                  {testedFarhan && (
                    <span className={`formula-predicted-tag ${isDiff ? 'tag-error' : 'tag-ok'}`}>
                      Pred: {formulaPSI}
                    </span>
                  )}
                </div>
              );
            })}
          </div>

          {/* Generator Turbine Station */}
          <div className={`turbine-station ${turbineSpinning ? 'turbine-active' : ''}`}>
            <div className="turbine-wheel">
              <svg width="44" height="44" viewBox="0 0 44 44">
                <circle cx="22" cy="22" r="18" fill="none" stroke="#38bdf8" strokeWidth="3" />
                <path d="M22 4 L22 40 M4 22 L40 22 M9 9 L35 35 M9 35 L35 9" stroke="#38bdf8" strokeWidth="2.5" />
              </svg>
            </div>
            <span className="turbine-status-lbl">
              {turbineSpinning ? '⚡ TURBINE ONLINE' : 'TURBINE IDLE'}
            </span>
          </div>
        </div>

        {/* Live Coordinate Oscilloscope Monitor */}
        <div className="hydro-oscilloscope">
          <div className="osc-header">
            <span className="osc-title">📈 COORDINATE TELEMETRY: PRESSURE vs CHECKPOINT</span>
            <span className="osc-formula">Active: P = {currentFormula}</span>
          </div>
          <svg className="osc-graph-svg" viewBox="0 0 320 110">
            {/* Coordinate Grid lines */}
            <line x1="30" y1="90" x2="310" y2="90" stroke="rgba(255,255,255,0.15)" strokeWidth="1" />
            <line x1="30" y1="10" x2="30" y2="90" stroke="rgba(255,255,255,0.15)" strokeWidth="1" />
            <text x="20" y="20" fill="#64748b" fontSize="8">PSI</text>
            <text x="300" y="102" fill="#64748b" fontSize="8">Stn (n)</text>

            {/* Target sensor points (1 to 4) */}
            {[1, 2, 3, 4].map((stn) => {
              const x = 30 + stn * 60;
              const actualPSI = sys.a1 + (stn - 1) * sys.d;
              // Map PSI 0..40 to Y 90..15
              const y = 90 - (actualPSI / 40) * 75;
              return (
                <g key={stn}>
                  <circle cx={x} cy={y} r="4" fill="#38bdf8" />
                  <text x={x} y={y - 7} fill="#94a3b8" fontSize="8" textAnchor="middle">
                    ({stn}, {actualPSI})
                  </text>
                </g>
              );
            })}

            {/* Simulated Formula Line */}
            {(() => {
              const x1 = 30 + 1 * 60;
              const y1 = 90 - ((rateSlider * 1 + offsetSlider) / 40) * 75;
              const x4 = 30 + 4 * 60;
              const y4 = 90 - ((rateSlider * 4 + offsetSlider) / 40) * 75;
              return (
                <line
                  x1={x1}
                  y1={y1}
                  x2={x4}
                  y2={y4}
                  stroke={isPerfectMatch ? '#10e5a5' : '#f59e0b'}
                  strokeWidth="2.5"
                  strokeDasharray={isPerfectMatch ? 'none' : '4 3'}
                />
              );
            })()}
          </svg>
        </div>
      </div>

      {/* Guided Engineering Investigation Controls */}
      <div className="station-interactive-phases">
        {/* Step 1: The Farhan Dilemma — Test First Term Fallacy */}
        <div className={`investigation-card ${governorLocked ? 'is-complete' : 'is-active'}`}>
          <div className="inv-header">
            <span className="inv-step-num">1</span>
            <div className="inv-title-wrap">
              <h4 className="inv-title">Audit Farhan's Proposed Formula: {sys.farhanMistake}</h4>
              <p className="inv-desc">
                Farhan assumes the constant must be the first term ({sys.a1}). Test this in the simulator against Station 1!
              </p>
            </div>
            {governorLocked && <span className="inv-check-badge">✅ ZERO-TERM CALIBRATED</span>}
          </div>

          {!testedFarhan ? (
            <div className="inv-action-row">
              <button className="btn-action-warning" onClick={testFarhanFormula}>
                ⚠️ Run Farhan's Formula in Sensor Simulator
              </button>
            </div>
          ) : !governorLocked ? (
            <div className="tuner-manifold-box">
              <div className="tuner-sliders-grid">
                {/* Rate Slider (d) */}
                <div className="tuner-col">
                  <div className="tuner-label-row">
                    <span>Rate of Gain (d):</span>
                    <strong className="tuner-val-bold">{rateSlider} {sys.unit}/stn</strong>
                  </div>
                  <input
                    type="range"
                    min="2"
                    max="10"
                    value={rateSlider}
                    onChange={(e) => setRateSlider(parseInt(e.target.value, 10))}
                    className="slider-range"
                  />
                  <span className="slider-hint">Common difference between stations</span>
                </div>

                {/* Zero-Term Offset Slider (c = a1 - d) */}
                <div className="tuner-col">
                  <div className="tuner-label-row">
                    <span>Zero-Term Constant (c):</span>
                    <strong className={`tuner-val-bold ${offsetSlider === sys.zeroTerm ? 'highlight-correct' : ''}`}>
                      {offsetSlider} {sys.unit}
                    </strong>
                  </div>
                  <input
                    type="range"
                    min="0"
                    max="25"
                    value={offsetSlider}
                    onChange={(e) => setOffsetSlider(parseInt(e.target.value, 10))}
                    className="slider-range"
                  />
                  <span className="slider-hint">Must equal Station 1 − d ({sys.a1} − {sys.d} = {sys.zeroTerm})</span>
                </div>
              </div>

              {/* Real-time Formula Test Readout */}
              <div className="formula-eval-bar">
                <span className="eval-eq">Testing at Station 1: {rateSlider}(1) + {offsetSlider} = <strong>{predictedAt1} {sys.unit}</strong></span>
                <span className={`eval-status ${predictedAt1 === sys.a1 ? 'eval-ok' : 'eval-bad'}`}>
                  {predictedAt1 === sys.a1 ? `✅ MATCHES SENSOR (${sys.a1} ${sys.unit})` : `❌ MISMATCH (Actual is ${sys.a1})`}
                </span>
                <button
                  className="btn-action-primary"
                  onClick={handleLockGovernor}
                  disabled={!isPerfectMatch}
                >
                  Synchronize Governor
                </button>
              </div>
            </div>
          ) : (
            <div className="inv-success-pill">
              <span>Governor locked to true general term: <strong>P_n = {sys.d}n + {sys.zeroTerm}</strong>. Zero-term constant calibrated!</span>
            </div>
          )}
        </div>

        {/* Step 2: Calibrate High-Pressure Deep Station 35 */}
        {governorLocked && (
          <div className={`investigation-card ${success ? 'is-complete' : 'is-active'}`}>
            <div className="inv-header">
              <span className="inv-step-num">2</span>
              <div className="inv-title-wrap">
                <h4 className="inv-title">Deep Alpine Turbine Mission: Calculate Station {sys.targetStation}</h4>
                <p className="inv-desc">
                  To prevent turbine blade rupture, pre-pressurize the hydraulic line for <strong>Station {sys.targetStation}</strong>.
                </p>
              </div>
              {success && <span className="inv-check-badge">🏆 GENERATORS ONLINE</span>}
            </div>

            {!success ? (
              <div className="inv-action-row">
                <div className="far-term-solver">
                  <div className="solver-hint-math">
                    <code>P_{sys.targetStation} = {sys.d}({sys.targetStation}) + {sys.zeroTerm} = ? {sys.unit}</code>
                  </div>
                  <div className="flex-input-grp">
                    <input
                      type="number"
                      className="telemetry-input large"
                      placeholder={`Target pressure for Stn ${sys.targetStation}...`}
                      value={deepInput}
                      onChange={(e) => setDeepInput(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleCheckDeepTarget()}
                    />
                    <button className="btn-action-primary glow" onClick={handleCheckDeepTarget}>
                      ⚡ Engage Turbine Governor
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              <div className="inv-success-pill celebration">
                <span>💧 Station {sys.targetStation} pressurized to exact {sys.targetCorrect} {sys.unit}! Emergency hydroelectric power restored!</span>
              </div>
            )}
          </div>
        )}

        {/* Live Feedback Alert */}
        {feedback && (
          <div className={`station-feedback-alert ${feedback.type === 'ok' ? 'alert-success' : 'alert-error'}`}>
            <span className="alert-icon">{feedback.type === 'ok' ? '✨' : '⚠️'}</span>
            <span className="alert-msg">{feedback.text}</span>
          </div>
        )}

        {/* Project Switcher */}
        <div className="station-sub-actions">
          <button className="btn-subtle" onClick={nextSystem}>
            🔄 Switch Hydraulic System ({sys.name})
          </button>
        </div>
      </div>
    </div>
  );
}
