// src/config/worlds.config.js
export const WORLDS = [
  {
    id: 0,
    name: 'First Steps on the Trail',
    emoji: '🌫️',
    accent: 'var(--world-0)',
    description: 'Continue a number pattern and state the next term(s)',
    conceptFocus: 'continue-pattern',
    boss: { name: 'The Vanishing Trail', emoji: '🌫️', reward: 'Trailblazer Badge' },
  },
  {
    id: 1,
    name: 'Reading the Trail Markers',
    emoji: '🗣️',
    accent: 'var(--world-1)',
    description: "Describe a pattern's term-to-term rule in words",
    conceptFocus: 'describe-rule-words',
    boss: { name: 'The Riddle Ranger', emoji: '🗣️', reward: 'Wordsmith Badge' },
  },
  {
    id: 2,
    name: 'Special Landmarks',
    emoji: '🔺',
    accent: 'var(--world-2)',
    description: 'Recognise even/odd/square/triangular/cube number sequences',
    conceptFocus: 'special-sequences',
    boss: { name: 'The Shape-Shifter Summit', emoji: '🔺', reward: 'Landmark Badge' },
  },
  {
    id: 3,
    name: 'Mapping the Rule',
    emoji: '🗺️',
    accent: 'var(--world-3)',
    description: 'Derive the algebraic general term of a linear sequence',
    conceptFocus: 'derive-general-term',
    boss: { name: 'The Formula Guardian', emoji: '🗺️', reward: 'Cartographer Badge' },
  },
  {
    id: 4,
    name: 'The Far Checkpoint',
    emoji: '⛰️',
    accent: 'var(--world-4)',
    description: 'Use the general term to find a far-ahead term',
    conceptFocus: 'apply-general-term-find-term',
    boss: { name: 'The Far Peak Sentinel', emoji: '⛰️', reward: 'Long-Range Badge' },
  },
  {
    id: 5,
    name: 'Is It on the Trail?',
    emoji: '🚧',
    accent: 'var(--world-5)',
    description: 'Use the general term to test sequence membership',
    conceptFocus: 'test-membership',
    boss: { name: "The Gatekeeper's Riddle", emoji: '🚧', reward: 'Verifier Badge' },
  },
  {
    id: 6,
    name: 'Building the Campsite',
    emoji: '⛺',
    accent: 'var(--world-6)',
    description: 'Translate a growing figure pattern into a sequence + general term',
    conceptFocus: 'figure-pattern-linear',
    boss: { name: 'The Campsite Collapse', emoji: '⛺', reward: 'Builder Badge' },
  },
  {
    id: 7,
    name: 'The Growing Staircase',
    emoji: '🪜',
    accent: 'var(--world-7)',
    description: 'A second, slightly harder figure-pattern world',
    conceptFocus: 'figure-pattern-applied',
    boss: { name: 'The Staircase Spirit', emoji: '🪜', reward: 'Architect Badge' },
  },
  {
    id: 8,
    name: 'Expedition Countdown',
    emoji: '⏳',
    accent: 'var(--world-8)',
    description: 'Full multi-step real-world prediction using the general term',
    conceptFocus: 'multi-step-applied-prediction',
    boss: { name: 'The Countdown Keeper', emoji: '⏳', reward: 'Forecaster Badge' },
  },
  {
    id: 9,
    name: 'The Summit Challenge',
    emoji: '🏔️',
    accent: 'var(--world-9)',
    description: 'Mixed review of every concept above',
    conceptFocus: 'mixed-review',
    boss: { name: 'The Summit Master', emoji: '🏔️', reward: 'Expedition Champion Trophy' },
  },
];

export const PLAY_MODES = [
  {
    id: 'guided',
    name: 'Guided Practice',
    icon: '🧭',
    desc: '5 questions with hints, no time pressure',
    questionCount: 5,
    hints: true,
    timed: false,
    lives: false,
  },
  {
    id: 'independent',
    name: 'Independent Practice',
    icon: '✍️',
    desc: '10 questions, no hints, full XP',
    questionCount: 10,
    hints: false,
    timed: false,
    lives: false,
  },
  {
    id: 'timed',
    name: 'Timed Challenge',
    icon: '⏱️',
    desc: '8 questions in 60 seconds, bonus XP',
    questionCount: 8,
    hints: false,
    timed: true,
    timeLimit: 60,
    lives: false,
  },
  {
    id: 'boss',
    name: 'Boss Battle',
    icon: '👑',
    desc: '5 questions, 3 lives — defeat the boss!',
    questionCount: 5,
    hints: false,
    timed: false,
    lives: true,
  },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 20,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};
