// Auto-generated by generate_audio.js — DO NOT hand-edit.
// This map starts empty because no ElevenLabs API key was available in this build
// environment. Run `npm run generate-audio` locally with a valid VITE_ELEVENLABS_API_KEY
// (see .env.local.example) to populate this file and pre-generate all fixed narration
// audio into public/assets/audio/. Until then, narration falls through to the dynamic
// ElevenLabs path at runtime (or is skipped silently if no API key is present client-side —
// see audio_generation_pipeline.md, "No Browser Fallback").

export const audioMap = {};

export default audioMap;
